export { firebaseApp, firebaseAuth, realtimeDb, firestore } from './config';
export { authService } from './authService';
export type { FirebaseUser } from './authService';
export { userRepository } from './userRepository';
export { friendRepository } from './friendRepository';
export { matchHistoryRepository } from './matchHistoryRepository';
export { gameRepository } from './gameRepository';
export { gameFunctions } from './gameFunctions';
export { callable } from './callable';
export type { CallResult, CallErrorCode } from './callable';
export { serverNow, clockSkewMs } from './serverTime';
export { roomRepository } from './roomRepository';
export { matchmakingRepository } from './matchmakingRepository';
export { presenceRepository } from './presenceRepository';
export type { PresenceState } from './presenceRepository';
export { messagingService } from './messagingService';
export { Collections, RtdbPaths } from './paths';
